### ISSUE TITLE
Initial todo idea

### ISSUE THREAD

**Issue by giannoulakis** [bullettext/bullettext#1]
Reference: 
https://roamresearch.com/#/app/help/page/dxTi-iUs2

Main functionalities
- [ ] automatically create note for the day
- [ ] list note references
- [ ] link block to note , using brackets [[note]] - a block can reference multiple notes
- [ ] menu when pressing / listing all commands
  - [ ] add todo
  - [ ] link to a note (search as you type)
  - [ ] date picker 
- [ ] when keydown [, add closing bracket
- [ ] when typing double brackets, show page reference menu(with search)
- [ ] select multiple blocks
- [ ] copy/cut and paste block(s)
- [ ] global search 
  - [ ] first search on title (all note titles are in memory)
  - [ ] then ajax call with search text to list blocks
- [ ] focus on a block
- [ ] toggle to close child blocks
- [ ] import from roamresearch
- [ ] dragndrop to reorder blocks

Future:
- [ ] api
- [ ] public notes - read only
- [ ] colaboration
